using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace EvolveCentral.Helper
{
    public static class Constant
    {

        //SESSION ADMINISTRATOR ACCOUNT
        public static string CODE_SESSION_CURRENTADMINISTRATORACCOUNTID = "CODE_SESSION_CURRENTADMINISTRATORACCOUNTID";
        public static string CODE_SESSION_CURRENTADMINISTRATORACCOUNTNAME = "CODE_SESSION_CURRENTADMINISTRATORACCOUNTNAME";
      
        public static string CODE_SESSION_CURRENTADMINISTRATORROLEID = "CODE_SESSION_CURRENTADMINISTRATORROLEID";
        public static string CODE_SESSION_CURRENTADMINISTRATORROLECODE = "CODE_SESSION_CURRENTADMINISTRATORROLECODE";

        public static string CODE_SESSION_CURRENTADMINISTRATORPERMISSIONCODELIST = "CODE_SESSION_CURRENTADMINISTRATORPERMISSIONCODELIST";

        //SESSION MEMBER ACCOUNT
        public static string CODE_SESSION_CURRENTMEMBERACCOUNTID = "CODE_SESSION_CURRENTMEMBERACCOUNTID";
        public static string CODE_SESSION_CURRENTMEMBERACCOUNTNAME = "CODE_SESSION_CURRENTMEMBERACCOUNTNAME";
  
    //ROLE CODE
        public static string CODE_ROLE_DEVELOPER = "DEVELOPER";
        public static string CODE_ROLE_SUPERADMINISTRATOR = "SADMIN";

        //SERVICE CODE
        public static string CODE_SERVICE_CRMEVOLUTION = "SYNC_CRM_EVOLUTION";
      
    }
}