//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentralConsole.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyItem
    {
        public CompanyItem()
        {
            this.MemberAccountItems = new HashSet<MemberAccountItem>();
            this.ServiceCrmEvolutionItems = new HashSet<ServiceCrmEvolutionItem>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<MemberAccountItem> MemberAccountItems { get; set; }
        public virtual ICollection<ServiceCrmEvolutionItem> ServiceCrmEvolutionItems { get; set; }
    }
}
