//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentralConsole.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTemplateCrmEvolutionDetailItem
    {
        public int Id { get; set; }
        public int ServiceTemplateCrmEvolutionId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string SourceTable { get; set; }
        public string DestinationTable { get; set; }
        public string CommandType { get; set; }
        public string Command { get; set; }
        public string Description { get; set; }
        public int Sequence { get; set; }
        public bool IsActive { get; set; }
        public int LastModifiedAdministratorAccountId { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual ServiceTemplateCrmEvolutionItem ServiceTemplateCrmEvolutionItem { get; set; }
    }
}
