//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentralConsole.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTypeItem
    {
        public ServiceTypeItem()
        {
            this.ServiceTemplateCrmEvolutionItems = new HashSet<ServiceTemplateCrmEvolutionItem>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Decription { get; set; }
    
        public virtual ICollection<ServiceTemplateCrmEvolutionItem> ServiceTemplateCrmEvolutionItems { get; set; }
    }
}
