//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentralConsole.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncLogCrmEvolutionDetailItem
    {
        public int Id { get; set; }
        public Nullable<int> SyncLogCrmEvolutionId { get; set; }
        public string ExecutedCommand { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsSuccessful { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual SyncLogCrmEvolutionItem SyncLogCrmEvolutionItem { get; set; }
    }
}
