//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorAccountItem
    {
        public AdministratorAccountItem()
        {
            this.ApplicationLogItems = new HashSet<ApplicationLogItem>();
        }
    
        public int Id { get; set; }
        public string Password { get; set; }
        public int AdministratorRoleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeletable { get; set; }
        public Nullable<System.DateTime> LastLogonOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual AdministratorRoleItem AdministratorRoleItem { get; set; }
        public virtual ICollection<ApplicationLogItem> ApplicationLogItems { get; set; }
    }
}
