//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorRoleItem
    {
        public AdministratorRoleItem()
        {
            this.AdministratorAccountItems = new HashSet<AdministratorAccountItem>();
            this.AdministratorPermissionItems = new HashSet<AdministratorPermissionItem>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public string Description { get; set; }
        public bool IsDeletable { get; set; }
    
        public virtual ICollection<AdministratorAccountItem> AdministratorAccountItems { get; set; }
        public virtual ICollection<AdministratorPermissionItem> AdministratorPermissionItems { get; set; }
    }
}
