//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceCrmEvolutionDetailHistoryItem
    {
        public int Id { get; set; }
        public int ServiceCrmEvolutionDetailId { get; set; }
        public string Code { get; set; }
        public int ServiceCrmEvolutionId { get; set; }
        public string Name { get; set; }
        public string SourceTable { get; set; }
        public string DestinationTable { get; set; }
        public string CommandType { get; set; }
        public string Command { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sequence { get; set; }
        public bool IsUnique { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> LastModifiedMemberAccountId { get; set; }
        public Nullable<int> LastModifiedAdministratorAccountId { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual ServiceCrmEvolutionDetailItem ServiceCrmEvolutionDetailItem { get; set; }
        public virtual ServiceCrmEvolutionItem ServiceCrmEvolutionItem { get; set; }
    }
}
