//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceTemplateCrmEvolutionItem
    {
        public ServiceTemplateCrmEvolutionItem()
        {
            this.ServiceCrmEvolutionItems = new HashSet<ServiceCrmEvolutionItem>();
            this.ServiceTemplateCrmEvolutionDetailItems = new HashSet<ServiceTemplateCrmEvolutionDetailItem>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int ServiceTypeId { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ServiceCrmEvolutionItem> ServiceCrmEvolutionItems { get; set; }
        public virtual ICollection<ServiceTemplateCrmEvolutionDetailItem> ServiceTemplateCrmEvolutionDetailItems { get; set; }
        public virtual ServiceTypeItem ServiceTypeItem { get; set; }
    }
}
