//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvolveCentral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SyncLogCrmEvolutionItem
    {
        public SyncLogCrmEvolutionItem()
        {
            this.SyncLogCrmEvolutionDetailItems = new HashSet<SyncLogCrmEvolutionDetailItem>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ServiceCrmEvolutionId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsSuccessful { get; set; }
    
        public virtual ICollection<SyncLogCrmEvolutionDetailItem> SyncLogCrmEvolutionDetailItems { get; set; }
    }
}
